### ISSUE TITLE
CarbonBehavior: Problem with yii\db\Expression

### ISSUE THREAD

**Issue by Bhoft** [yii2mod/yii2-behaviors#1]
Hi I have tested your CarbonBehavior and would find it quite usefull.

But i have an issue when saving new db entries. 

In my Model i have this behavior settting:

     [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                'value' => new yii\db\Expression('UTC_TIMESTAMP()'),
      ],
      'carbon' => [
                'class' => CarbonBehavior::className(),
                'attributes' => [
                    'created_at',
                    'updated_at',
                ]
            ],

When i now save an model e.g. the updated_at value is a db expression, which yours CarbonBehavior fails to accept.

This is what throws the exception 

    InvalidArgumentException
    A four digit year could not be found
    Data missing.

    call_user_func([yii2mod\behaviors\CarbonBehavior, 'attributesToCarbon'], yii\db\AfterSaveEvent) 
    yii2mod\yii2-behaviors\CarbonBehavior.php at line 105 – Carbon\Carbon::createFromFormat('Y-m-d H:i:s', yii\db\Expression) 

I there a possibility to disable the AfterSaveEvent ?
How do you set your created_at/ updated_at on beforeInsert/beforeUpdate?
do you just use `Carbon\Carbon::now()` ?

thanks in advance

**Comment by ihorchepurnyi** [comment]
You can fix it by the following configuration:
```php
            [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                'value' => Carbon::now('UTC')->toDateTimeString(),
            ],
            'carbon' => [
                'class' => CarbonBehavior::class,
                'attributes' => [
                    'created_at',
                    'updated_at',
                ]
            ],
```

> Basically you need to change ` new yii\db\Expression('UTC_TIMESTAMP()'),` -> `Carbon::now('UTC')->toDateTimeString()`

**Comment by Bhoft** [comment]
Thanks that solves this issue
