### ISSUE TITLE
issues with different phpversions

### ISSUE THREAD

**Issue by Bhoft** [yii2mod/yii2-behaviors#3]
Hi i have issues with different behaviour of the Carbonbehaviour when using different php versions.

Background: i have a wamp installation where i can easily switch between different php versions.
All have the same php.ini settings and also the application is the same.

I am using the CarbonBehavior as followed in my Model class:

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['carbon'] = [
                'class' => CarbonBehavior::className(),
                'attributes' => [
                    'review_start',
                    'review_end',
                    'crf_review_start',
                    'crf_review_end',
                    'created_at',
                    'updated_at',
                ]
            ];
        return $behaviors;
    }

The columns are all of type `datetime`.

I have different "output" of the attributes depending on the php version I use.

PHP 7.1.27:

    $this->crf_review_end
    Carbon\Carbon#1
    (
        [date] => '2019-03-13 07:55:12.000000'
        [timezone_type] => 3
        [timezone] => 'UTC'
    )
    $this->crf_review_end->utc
        true

    $this->crf_review_end->local
       true

    date_default_timezone_get()
       'UTC'
    
PHP 7.2.16 + PHP 7.3.3:

    $this->crf_review_end
    Carbon\Carbon#1
    (
        [date] => '2019-03-13 08:55:12.000000'
        [timezone_type] => 3
        [timezone] => 'Europe/Berlin'
    )
    $this->crf_review_end->utc
        false

    $this->crf_review_end->local
        false

    date_default_timezone_get()
       'UTC'

     

Without Carbon (Stored the UTC value)

     $this->crf_review_end
     '2019-03-13 07:55:12'

Displayed on the widget formatted into the Berlin Timezone => Mar 13, 2019 8:55:12 AM

As the php settings are all the same i don't know where the Problem could be.

Is there a reason that the Carbon extensions used is limited to "nesbot/carbon": "~1.0"  in the composer.json file?

The installed version is of the "nesbot/carbon" is `1.36.2` where the latest version is `2.16.0`.

from php.ini:

    Timezone Database | internal
    Default timezone | UTC
    date.timezone | UTC
    $_SERVER['FORMATER_DEFAULT_TIMEZONE'] | UTC
    $_SERVER['FORMATER_TIMEZONE'] | Europe/Berlin

As I understand Carbon 1.x should be used for php versions < 7.1 and Carbon 2 for >= 7.1.
But your behavior only uses the Carbon 1 version.

"Carbon 2 (requiring PHP >= 7.1) perfectly supports microseconds. But if you use Carbon 1 and PHP < 7.1, read our section about partial microseconds support."
https://carbon.nesbot.com/docs/

Sadly the Carbon 1 Version doesn't seem to work correctly for php >= 7.2.
Do you have an idea how this can be fixed?

**Comment by Bhoft** [comment]
Somehow Carbon uses the app->components->formatter->timezone setting with php 7.2.x / 7.3.x. Which is of course set to `Europe\Berlin`.

\Carbon\Carbon::now()  e.g. uses UTC as expected.

**Comment by ihorchepurnyi** [comment]
Hi @Bhoft, maybe this issue related to server settings or Carbon

**Comment by ihorchepurnyi** [comment]
I don't see the way how we can fix it in the `CarbonBehavior`

**Comment by Bhoft** [comment]
I have just realized that my local wampserver installation doesn't seems to load e.g. the php_intl extension even if no error is shown.
So maybe the "problem" is somewhere else.
I will first have to check this. if this error was because of the wampserver i will reply.

**Comment by Bhoft** [comment]
It was indeed a mixture of the change of how php loads extensions
7.1. => extension=php_intl.dll
7.2+ => extension=intl

and an older wampserver version which displayed the extensions as loaded but they aren't.
Now that i have updated the wampserver and fixed the php.ini for the 7.2 load format everything works as it should!

Forgot to mention the Problem was caused be the not loaded php_intl extension.

This really caused me some headaches. ;)
